---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "admin-config-default"}'
  namespace: logs
  name: event-validation-viewer
  labels:
    app.kubernetes.io/name: event-validation-viewer
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: event-validation-viewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-validation-viewer
  namespace: logs
  labels:
    app.kubernetes.io/name: event-validation-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-validation-viewer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-validation-viewer
    spec:
      nodeSelector:
        serviceType: admin-dependencies
      containers:
        - name: event-validation-viewer
          image: "asia.gcr.io/nextgen-devenv/nextgen-dev-testing-event-validation-viewer:1.0.1"
          imagePullPolicy: Always
          env:
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: POSTGRES_PORT
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
